### ISSUE TITLE
[Android Bootcamp] Team Project - Group 8 : First Walkthrough is ready for review

### ISSUE THREAD

**Issue by Oneill38** [CodePathTeam8/sightseeing-app#8]
Please review /cc @codepathreview @codepath. This is first walkthrough of our app with basic functionality added.  
![sightseeing_walkthrough](https://cloud.githubusercontent.com/assets/6576820/17874992/143099c0-689d-11e6-9600-a4a86dd5d445.gif)

**Comment by codepathreview** [comment]
:+1: Nice work creating tasks for sprint 1. The goal of this sprint is to have the basic screens and workflows ready as much as possible. A few notes
- Consider diving a bigger parent task into a number of smaller subtasks - provides a better picture of the progress on the issue.
- Good work dividing tasks among team members. This is critical in working as a team and also gives equal learning opportunity to everyone involved
- Make sure to keep your [milestones](https://github.com/CodePathTeam8/sightseeing-app/milestones) on track and create one for Sprint 2 (week 6).
- Work load needs to be divided equally among all members of the team. This is critical in working as a team and also gives equal learning opportunity to everyone involved. Good to see everyone [contributing](https://github.com/CodePathTeam8/sightseeing-app/graphs/contributors) to the project.
- Keep your project [README](https://github.com/CodePathTeam8/sightseeing-app/blob/master/README.md) updated at all times.
- Depending on the strategy your group has come up with, consider creating regular check ins to sync up your code to avoid having multiple errors at the end.
- Consider creating tasks to QA the app a few times to check the basic flow. Integration testing will especially be important for this project since each team member is working on a separate module. The best part is seeing it all come together into a polished app.

Consider incorporating as many screens as possible in this sprint so you can have enough time to add UI polish and advanced features later on. It is those little extra things you do that make everything feel more polished and desirable to use. Look forward to what you all come up with.
